apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      batch: nginx
  template:
    metadata:
      name: nginx
      labels:
        batch: nginx
    spec:
      containers:
      - name: nginx
        image: nginx
    
---

apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selector:
     batch: nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80