apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
spec:
  replicas: 
  selector:
    matchLabels:
      batch: redis
  template:
    metadata:
      name: redis
      labels:
        batch: redis
    spec:
      containers:
      - name: redis
        image: redis:alpine

---

apiVersion: v1
kind: Service
metadata:
  name: redis-service
spec:
  selector:
     batch: redis
  ports:
    - protocol: TCP
      port: 80
      targetPort: 6379
    