apiVersion: apps/v1
kind: Deployment
metadata:
  name: vote2
spec:
  replicas: 1
  selector:
    matchLabels:
      batch: vote2
  template:
    metadata:
      name: vote
      labels:
        batch: vote2
    spec:
      containers:
      - name: vote2
        image: dipesh017/demo:vote
      
        

     
    