apiVersion: apps/v1
kind: Deployment
metadata:
  name: vote2
spec:
  replicas: 1
  selector:
    matchLabels:
      batch: vote2
  template:
    metadata:
      name: vote
      labels:
        batch: vote2
    spec:
      containers:
      - name: vote2
        image: dipesh017/demo:vote
---      

apiVersion: v1
kind: Service
metadata:
  name: vote-service
spec:
  type: LoadBalancer
  selector:
     batch: vote
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80   

     
    