apiVersion: apps/v1
kind: Deployment
metadata:
  name: vote2
spec:
  replicas: 2
  selector:
    matchLabels:
      batch: vote2
  template:
    metadata:
      name: vote
      labels:
        batch: vote2
    spec:
      containers:
      - name: vote2
        image: dipesh017/demo:vote
        resources:
          requests:
            memory: "10Gi"
            cpu: "5"
          limits:
            memory: "8Gi"
            cpu: "4Gi"
---      

apiVersion: v1
kind: Service
metadata:
  name: vote-service
spec:
  type: LoadBalancer
  selector:
     batch: vote
  ports:
    - protocol: TCP
      #any port 
      port: 80
      #application port running on container
      targetPort: 80   

     
    