apiVersion: apps/v1
kind: Deployment
metadata:
  name: vote2
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 100%
      maxUnavailable: 0%
  replicas: 2
  selector:
    matchLabels:
      batch: vote2
  template:
    metadata:
      name: vote
      labels:
        batch: vote2
    spec:
      containers:
      - name: vote2
        image: nginx
        resources:
          requests:
            memory: ".1Gi"
            cpu: ".2"
          limits:
            memory: "20Gi"
            cpu: "10Gi"
---      

apiVersion: v1
kind: Service
metadata:
  name: vote-service
spec:
  type: LoadBalancer
  selector:
     batch: vote
  ports:
    - protocol: TCP
      #any port 
      port: 80
      #application port running on container
      targetPort: 80   

     
    