apiVersion: apps/v1
kind: Deployment
metadata:
  name: vote
spec:
  replicas: 1
  selector:
    matchLabels:
      batch: c38
  template:
    metadata:
      name: vote
      labels:
        batch: c38
    spec:
      containers:
      - name: voting
        image: dipesh017/demo:vote
        ports:
          - containerPort: 8080
            name: voting
       
        

     
    